---
# Update system
- include: update-system.yml
  when: system_update
  tag:
    - update
# Manage package (install/remove)
- include: manage-packages.yml
  tag:
    - package
# Clean system (include old kernels)
- include: clean-system.yml
  when: system_clean
  tag:
    - clean