---
# Update system
- include_tasks: update-system.yml
  when: system_update
  tags:
    - manage-system-update
# Manage package (install/remove)
- include: manage-packages.yml
  tags:
    - manage-system-package
# Clean system (include old kernels)
- include_tasks: clean-system.yml
  when: system_clean
  tags:
    - manage-system-clean