# Debian or Ubuntu
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Check if there are available updates
  command: /usr/lib/update-notifier/apt-check --package-names
  register: pkg_list_to_update

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true
  when: not system_update_security_only and pkg_list_to_update.stderr != "" and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Update security packages
  apt:
    upgrade: safe
  become: true
  when: system_update_security_only and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')


# CentOS or RHEL
- name: Update yum cache
  yum:
    update_cache: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Update all packages to the latest version
  yum:
    name: '*'
    state: latest
    disablerepo: base, extras, updates
  become: true
  when: not system_update_security_only ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Update security packages only
  yum:
    name: '*'
    state: latest
    security: yes
    disablerepo: base, extras, updates
  become: true
  when: system_update_security_only ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
